title: Noticias
modelClass: Spmda\Noticias\Models\Noticia
list: $/spmda/noticias/models/noticia/columns.yaml
recordUrl: 'spmda/noticias/noticias/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
